In [ ]:
from huggingface_hub import hf_hub_download
import torch
from transformers import PatchTSTConfig, PatchTSTForPrediction
import pandas as pd
import numpy as np
from datetime import timedelta

In [ ]:
context_length = 8

In [ ]:
data = pd.read_csv("./data/time_series.csv", parse_dates=["date"]).iloc[-context_length:]
data = data.drop(columns=["date"])
display(data)

In [ ]:
display(data.shape)

In [ ]:
tensor = torch.tensor(data.values).view(1, 8, 31).float()

In [ ]:
model = PatchTSTForPrediction.from_pretrained("../spark/model")

In [ ]:
outputs = model(past_values=tensor)

In [ ]:
predictions = outputs.prediction_outputs

In [ ]:
predictions_array = predictions.detach().numpy()

In [ ]:
print(predictions_array)

In [1]:
from huggingface_hub import hf_hub_download
import torch
from transformers import PatchTSTConfig, PatchTSTForPrediction
import pandas as pd
import numpy as np
from datetime import timedelta

In [8]:
def parse_result(prediction):
    return [int(x + 0.5) if x >= 0 else 0 for x in prediction]

In [21]:
model = PatchTSTForPrediction.from_pretrained("../spark/model")

num_predictions = 10
context_length = 8


df = pd.read_csv("./data/time_series.csv", parse_dates=["date"]).iloc[-context_length:]
last_date = df['date'].iloc[-1]
df = df.drop(columns=["date"])



for i in range(num_predictions):
    
    display(df)
    
    past_values = torch.tensor(df.values).view(1, 8, 31).float()    
    outputs = model(past_values=past_values)
    
    predictions_tensor = outputs.prediction_outputs[0]
    predictions = predictions_tensor.detach().numpy()
    
    for i, prediction in enumerate(predictions):
        date = last_date + timedelta(days=i + 1)
        prediction_array = parse_result(prediction)
        print(date, prediction_array)
        
        # Aggiungi una nuova riga alla fine del dataframe
        df.loc[len(df)] = prediction_array
        
        # Rimuovi la riga più vecchia (la prima)
        df = df.iloc[1:].reset_index(drop=True)
    
    # Aggiorna last_date per la prossima iterazione di previsione
    last_date += timedelta(days=len(predictions))

    # Copia il dataframe per evitare modifiche non intenzionali
    df = df.copy()

,1,2,3,4,5,6,7,8,9,10,...,22,23,24,25,26,27,28,29,30,31
1087,0.0,2.0,1.0,4.0,3.0,3.0,0.0,0.0,0.0,13.0,...,3.0,6.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
1088,0.0,1.0,3.0,4.0,7.0,3.0,1.0,0.0,0.0,10.0,...,3.0,10.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1089,1.0,2.0,1.0,5.0,4.0,6.0,0.0,0.0,0.0,13.0,...,5.0,11.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
1090,1.0,0.0,3.0,6.0,9.0,9.0,2.0,0.0,0.0,19.0,...,6.0,29.0,0.0,0.0,0.0,0.0,3.0,1.0,0.0,0.0
1091,0.0,1.0,4.0,9.0,6.0,8.0,0.0,0.0,0.0,9.0,...,9.0,16.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
1092,0.0,0.0,2.0,7.0,5.0,2.0,0.0,0.0,0.0,14.0,...,4.0,17.0,0.0,0.0,0.0,0.0,0.0,3.0,0.0,0.0
1093,0.0,1.0,4.0,11.0,2.0,6.0,0.0,0.0,0.0,12.0,...,2.0,14.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1094,0.0,0.0,2.0,6.0,2.0,5.0,1.0,0.0,1.0,10.0,...,0.0,11.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

2024-01-01 00:00:00 [0, 1, 3, 6, 5, 5, 1, 0, 0, 12, 0, 4, 1, 2, 1, 0, 3, 2, 7, 1, 0, 4, 14, 0, 0, 0, 0, 1, 0, 0, 0]
2024-01-02 00:00:00 [0, 1, 2, 7, 5, 5, 0, 0, 0, 12, 0, 4, 1, 2, 1, 0, 3, 2, 7, 1, 0, 4, 13, 0, 0, 0, 0, 1, 1, 0, 0]

,1,2,3,4,5,6,7,8,9,10,...,22,23,24,25,26,27,28,29,30,31
0,1.0,2.0,1.0,5.0,4.0,6.0,0.0,0.0,0.0,13.0,...,5.0,11.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
1,1.0,0.0,3.0,6.0,9.0,9.0,2.0,0.0,0.0,19.0,...,6.0,29.0,0.0,0.0,0.0,0.0,3.0,1.0,0.0,0.0
2,0.0,1.0,4.0,9.0,6.0,8.0,0.0,0.0,0.0,9.0,...,9.0,16.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
3,0.0,0.0,2.0,7.0,5.0,2.0,0.0,0.0,0.0,14.0,...,4.0,17.0,0.0,0.0,0.0,0.0,0.0,3.0,0.0,0.0
4,0.0,1.0,4.0,11.0,2.0,6.0,0.0,0.0,0.0,12.0,...,2.0,14.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5,0.0,0.0,2.0,6.0,2.0,5.0,1.0,0.0,1.0,10.0,...,0.0,11.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6,0.0,1.0,3.0,6.0,5.0,5.0,1.0,0.0,0.0,12.0,...,4.0,14.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
7,0.0,1.0,2.0,7.0,5.0,5.0,0.0,0.0,0.0,12.0,...,4.0,13.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0

2024-01-03 00:00:00 [0, 1, 3, 7, 5, 6, 1, 0, 0, 13, 0, 4, 1, 2, 2, 0, 5, 3, 8, 1, 0, 4, 18, 0, 0, 0, 0, 1, 1, 0, 0]
2024-01-04 00:00:00 [0, 1, 3, 7, 5, 6, 1, 0, 0, 12, 0, 3, 1, 2, 1, 0, 4, 3, 8, 1, 0, 4, 16, 0, 0, 0, 0, 1, 0, 0, 0]

,1,2,3,4,5,6,7,8,9,10,...,22,23,24,25,26,27,28,29,30,31
0,0.0,1.0,4.0,9.0,6.0,8.0,0.0,0.0,0.0,9.0,...,9.0,16.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
1,0.0,0.0,2.0,7.0,5.0,2.0,0.0,0.0,0.0,14.0,...,4.0,17.0,0.0,0.0,0.0,0.0,0.0,3.0,0.0,0.0
2,0.0,1.0,4.0,11.0,2.0,6.0,0.0,0.0,0.0,12.0,...,2.0,14.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,2.0,6.0,2.0,5.0,1.0,0.0,1.0,10.0,...,0.0,11.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,1.0,3.0,6.0,5.0,5.0,1.0,0.0,0.0,12.0,...,4.0,14.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
5,0.0,1.0,2.0,7.0,5.0,5.0,0.0,0.0,0.0,12.0,...,4.0,13.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0
6,0.0,1.0,3.0,7.0,5.0,6.0,1.0,0.0,0.0,13.0,...,4.0,18.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0
7,0.0,1.0,3.0,7.0,5.0,6.0,1.0,0.0,0.0,12.0,...,4.0,16.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0

2024-01-05 00:00:00 [0, 1, 3, 7, 4, 5, 0, 0, 0, 12, 0, 3, 1, 2, 1, 0, 3, 2, 8, 1, 0, 4, 15, 0, 0, 0, 0, 1, 1, 0, 0]
2024-01-06 00:00:00 [0, 1, 3, 8, 4, 6, 0, 0, 0, 12, 0, 3, 1, 2, 1, 0, 4, 2, 8, 1, 0, 3, 14, 0, 0, 0, 0, 1, 1, 0, 0]

,1,2,3,4,5,6,7,8,9,10,...,22,23,24,25,26,27,28,29,30,31
0,0.0,1.0,4.0,11.0,2.0,6.0,0.0,0.0,0.0,12.0,...,2.0,14.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,2.0,6.0,2.0,5.0,1.0,0.0,1.0,10.0,...,0.0,11.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,1.0,3.0,6.0,5.0,5.0,1.0,0.0,0.0,12.0,...,4.0,14.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
3,0.0,1.0,2.0,7.0,5.0,5.0,0.0,0.0,0.0,12.0,...,4.0,13.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0
4,0.0,1.0,3.0,7.0,5.0,6.0,1.0,0.0,0.0,13.0,...,4.0,18.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0
5,0.0,1.0,3.0,7.0,5.0,6.0,1.0,0.0,0.0,12.0,...,4.0,16.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
6,0.0,1.0,3.0,7.0,4.0,5.0,0.0,0.0,0.0,12.0,...,4.0,15.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0
7,0.0,1.0,3.0,8.0,4.0,6.0,0.0,0.0,0.0,12.0,...,3.0,14.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0

2024-01-07 00:00:00 [0, 1, 3, 7, 4, 5, 1, 0, 0, 12, 0, 2, 1, 2, 1, 0, 4, 2, 7, 1, 0, 2, 14, 0, 0, 0, 0, 1, 0, 0, 0]
2024-01-08 00:00:00 [0, 1, 3, 7, 4, 5, 1, 0, 0, 12, 0, 3, 1, 2, 1, 0, 4, 2, 8, 1, 0, 4, 15, 0, 0, 0, 0, 1, 0, 0, 0]

,1,2,3,4,5,6,7,8,9,10,...,22,23,24,25,26,27,28,29,30,31
0,0.0,1.0,3.0,6.0,5.0,5.0,1.0,0.0,0.0,12.0,...,4.0,14.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
1,0.0,1.0,2.0,7.0,5.0,5.0,0.0,0.0,0.0,12.0,...,4.0,13.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0
2,0.0,1.0,3.0,7.0,5.0,6.0,1.0,0.0,0.0,13.0,...,4.0,18.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0
3,0.0,1.0,3.0,7.0,5.0,6.0,1.0,0.0,0.0,12.0,...,4.0,16.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
4,0.0,1.0,3.0,7.0,4.0,5.0,0.0,0.0,0.0,12.0,...,4.0,15.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0
5,0.0,1.0,3.0,8.0,4.0,6.0,0.0,0.0,0.0,12.0,...,3.0,14.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0
6,0.0,1.0,3.0,7.0,4.0,5.0,1.0,0.0,0.0,12.0,...,2.0,14.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
7,0.0,1.0,3.0,7.0,4.0,5.0,1.0,0.0,0.0,12.0,...,4.0,15.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0

2024-01-09 00:00:00 [0, 1, 3, 7, 5, 5, 1, 0, 0, 12, 0, 3, 1, 2, 1, 0, 4, 2, 8, 1, 0, 4, 14, 0, 0, 0, 0, 1, 1, 0, 0]
2024-01-10 00:00:00 [0, 1, 3, 7, 4, 5, 1, 0, 0, 12, 0, 3, 1, 2, 1, 0, 4, 2, 8, 1, 0, 4, 15, 0, 0, 0, 0, 1, 1, 0, 0]

,1,2,3,4,5,6,7,8,9,10,...,22,23,24,25,26,27,28,29,30,31
0,0.0,1.0,3.0,7.0,5.0,6.0,1.0,0.0,0.0,13.0,...,4.0,18.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0
1,0.0,1.0,3.0,7.0,5.0,6.0,1.0,0.0,0.0,12.0,...,4.0,16.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
2,0.0,1.0,3.0,7.0,4.0,5.0,0.0,0.0,0.0,12.0,...,4.0,15.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0
3,0.0,1.0,3.0,8.0,4.0,6.0,0.0,0.0,0.0,12.0,...,3.0,14.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0
4,0.0,1.0,3.0,7.0,4.0,5.0,1.0,0.0,0.0,12.0,...,2.0,14.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
5,0.0,1.0,3.0,7.0,4.0,5.0,1.0,0.0,0.0,12.0,...,4.0,15.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
6,0.0,1.0,3.0,7.0,5.0,5.0,1.0,0.0,0.0,12.0,...,4.0,14.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0
7,0.0,1.0,3.0,7.0,4.0,5.0,1.0,0.0,0.0,12.0,...,4.0,15.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0

2024-01-11 00:00:00 [0, 1, 3, 7, 4, 5, 1, 0, 0, 12, 0, 3, 1, 2, 1, 0, 4, 2, 8, 1, 0, 4, 15, 0, 0, 0, 0, 1, 1, 0, 0]
2024-01-12 00:00:00 [0, 1, 3, 7, 4, 5, 1, 0, 0, 12, 0, 3, 1, 2, 1, 0, 4, 2, 8, 1, 0, 4, 15, 0, 0, 0, 0, 1, 1, 0, 0]

,1,2,3,4,5,6,7,8,9,10,...,22,23,24,25,26,27,28,29,30,31
0,0.0,1.0,3.0,7.0,4.0,5.0,0.0,0.0,0.0,12.0,...,4.0,15.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0
1,0.0,1.0,3.0,8.0,4.0,6.0,0.0,0.0,0.0,12.0,...,3.0,14.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0
2,0.0,1.0,3.0,7.0,4.0,5.0,1.0,0.0,0.0,12.0,...,2.0,14.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
3,0.0,1.0,3.0,7.0,4.0,5.0,1.0,0.0,0.0,12.0,...,4.0,15.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
4,0.0,1.0,3.0,7.0,5.0,5.0,1.0,0.0,0.0,12.0,...,4.0,14.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0
5,0.0,1.0,3.0,7.0,4.0,5.0,1.0,0.0,0.0,12.0,...,4.0,15.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0
6,0.0,1.0,3.0,7.0,4.0,5.0,1.0,0.0,0.0,12.0,...,4.0,15.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0
7,0.0,1.0,3.0,7.0,4.0,5.0,1.0,0.0,0.0,12.0,...,4.0,15.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0

2024-01-13 00:00:00 [0, 1, 3, 7, 4, 5, 1, 0, 0, 12, 0, 3, 1, 2, 1, 0, 4, 2, 8, 1, 0, 3, 15, 0, 0, 0, 0, 1, 1, 0, 0]
2024-01-14 00:00:00 [0, 1, 3, 7, 4, 5, 1, 0, 0, 12, 0, 3, 1, 2, 1, 0, 4, 2, 8, 1, 0, 3, 15, 0, 0, 0, 0, 1, 1, 0, 0]

,1,2,3,4,5,6,7,8,9,10,...,22,23,24,25,26,27,28,29,30,31
0,0.0,1.0,3.0,7.0,4.0,5.0,1.0,0.0,0.0,12.0,...,2.0,14.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
1,0.0,1.0,3.0,7.0,4.0,5.0,1.0,0.0,0.0,12.0,...,4.0,15.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
2,0.0,1.0,3.0,7.0,5.0,5.0,1.0,0.0,0.0,12.0,...,4.0,14.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0
3,0.0,1.0,3.0,7.0,4.0,5.0,1.0,0.0,0.0,12.0,...,4.0,15.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0
4,0.0,1.0,3.0,7.0,4.0,5.0,1.0,0.0,0.0,12.0,...,4.0,15.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0
5,0.0,1.0,3.0,7.0,4.0,5.0,1.0,0.0,0.0,12.0,...,4.0,15.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0
6,0.0,1.0,3.0,7.0,4.0,5.0,1.0,0.0,0.0,12.0,...,3.0,15.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0
7,0.0,1.0,3.0,7.0,4.0,5.0,1.0,0.0,0.0,12.0,...,3.0,15.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0

2024-01-15 00:00:00 [0, 1, 3, 7, 4, 5, 1, 0, 0, 12, 0, 3, 1, 2, 1, 0, 4, 2, 8, 1, 0, 4, 15, 0, 0, 0, 0, 1, 1, 0, 0]
2024-01-16 00:00:00 [0, 1, 3, 7, 4, 5, 1, 0, 0, 12, 0, 3, 1, 2, 1, 0, 4, 2, 8, 1, 0, 4, 15, 0, 0, 0, 0, 1, 1, 0, 0]

,1,2,3,4,5,6,7,8,9,10,...,22,23,24,25,26,27,28,29,30,31
0,0.0,1.0,3.0,7.0,5.0,5.0,1.0,0.0,0.0,12.0,...,4.0,14.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0
1,0.0,1.0,3.0,7.0,4.0,5.0,1.0,0.0,0.0,12.0,...,4.0,15.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0
2,0.0,1.0,3.0,7.0,4.0,5.0,1.0,0.0,0.0,12.0,...,4.0,15.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0
3,0.0,1.0,3.0,7.0,4.0,5.0,1.0,0.0,0.0,12.0,...,4.0,15.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0
4,0.0,1.0,3.0,7.0,4.0,5.0,1.0,0.0,0.0,12.0,...,3.0,15.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0
5,0.0,1.0,3.0,7.0,4.0,5.0,1.0,0.0,0.0,12.0,...,3.0,15.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0
6,0.0,1.0,3.0,7.0,4.0,5.0,1.0,0.0,0.0,12.0,...,4.0,15.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0
7,0.0,1.0,3.0,7.0,4.0,5.0,1.0,0.0,0.0,12.0,...,4.0,15.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0

2024-01-17 00:00:00 [0, 1, 3, 7, 4, 5, 1, 0, 0, 12, 0, 3, 1, 2, 1, 0, 4, 2, 8, 1, 0, 4, 15, 0, 0, 0, 0, 1, 1, 0, 0]
2024-01-18 00:00:00 [0, 1, 3, 7, 4, 5, 1, 0, 0, 12, 0, 3, 1, 2, 1, 0, 4, 2, 8, 1, 0, 4, 15, 0, 0, 0, 0, 1, 1, 0, 0]

,1,2,3,4,5,6,7,8,9,10,...,22,23,24,25,26,27,28,29,30,31
0,0.0,1.0,3.0,7.0,4.0,5.0,1.0,0.0,0.0,12.0,...,4.0,15.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0
1,0.0,1.0,3.0,7.0,4.0,5.0,1.0,0.0,0.0,12.0,...,4.0,15.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0
2,0.0,1.0,3.0,7.0,4.0,5.0,1.0,0.0,0.0,12.0,...,3.0,15.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0
3,0.0,1.0,3.0,7.0,4.0,5.0,1.0,0.0,0.0,12.0,...,3.0,15.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0
4,0.0,1.0,3.0,7.0,4.0,5.0,1.0,0.0,0.0,12.0,...,4.0,15.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0
5,0.0,1.0,3.0,7.0,4.0,5.0,1.0,0.0,0.0,12.0,...,4.0,15.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0
6,0.0,1.0,3.0,7.0,4.0,5.0,1.0,0.0,0.0,12.0,...,4.0,15.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0
7,0.0,1.0,3.0,7.0,4.0,5.0,1.0,0.0,0.0,12.0,...,4.0,15.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0

2024-01-19 00:00:00 [0, 1, 3, 7, 4, 5, 1, 0, 0, 12, 0, 3, 1, 2, 1, 0, 4, 2, 8, 1, 0, 4, 15, 0, 0, 0, 0, 1, 1, 0, 0]
2024-01-20 00:00:00 [0, 1, 3, 7, 4, 5, 1, 0, 0, 12, 0, 3, 1, 2, 1, 0, 4, 2, 8, 1, 0, 4, 15, 0, 0, 0, 0, 1, 1, 0, 0]